// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtjq7RKE9W0k1n5hKPSmwd7ClqtP0ObtQ',
    appId: '1:1082380782716:web:b6b378fa88997cb4bd8df9',
    messagingSenderId: '1082380782716',
    projectId: 'counter-app-beginner',
    authDomain: 'counter-app-beginner.firebaseapp.com',
    storageBucket: 'counter-app-beginner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAglP__JvcKBInLSPBs5EcfSMJITvQJ2kY',
    appId: '1:1082380782716:android:6661f8ac1b913ebdbd8df9',
    messagingSenderId: '1082380782716',
    projectId: 'counter-app-beginner',
    storageBucket: 'counter-app-beginner.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdgJcBRNrlUBRpwtmDUZ29s2TNsINVKz8',
    appId: '1:1082380782716:ios:b4e3e26211a12a2bbd8df9',
    messagingSenderId: '1082380782716',
    projectId: 'counter-app-beginner',
    storageBucket: 'counter-app-beginner.firebasestorage.app',
    androidClientId: '1082380782716-3nhom26qm1bposnb1ac0su0qohfk9d1m.apps.googleusercontent.com',
    iosClientId: '1082380782716-a5lm4n2rn4gkqcb8ofa1muomfduv4r74.apps.googleusercontent.com',
    iosBundleId: 'com.example.counter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdgJcBRNrlUBRpwtmDUZ29s2TNsINVKz8',
    appId: '1:1082380782716:ios:b4e3e26211a12a2bbd8df9',
    messagingSenderId: '1082380782716',
    projectId: 'counter-app-beginner',
    storageBucket: 'counter-app-beginner.firebasestorage.app',
    androidClientId: '1082380782716-3nhom26qm1bposnb1ac0su0qohfk9d1m.apps.googleusercontent.com',
    iosClientId: '1082380782716-a5lm4n2rn4gkqcb8ofa1muomfduv4r74.apps.googleusercontent.com',
    iosBundleId: 'com.example.counter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtjq7RKE9W0k1n5hKPSmwd7ClqtP0ObtQ',
    appId: '1:1082380782716:web:ad76bf348f7745b1bd8df9',
    messagingSenderId: '1082380782716',
    projectId: 'counter-app-beginner',
    authDomain: 'counter-app-beginner.firebaseapp.com',
    storageBucket: 'counter-app-beginner.firebasestorage.app',
  );
}
